model_family: phi

LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

data_path: locuslab/TOFU
split: full
batch_size: 2
gradient_accumulation_steps: 8
num_epochs: 5
lr: 1e-5
save_dir: ../data/llm_weights/TOFU/ft_epoch${num_epochs}_lr${lr}_${model_family}_${split}_wd${weight_decay}

weight_decay: 0.01
seed: 42